### ISSUE TITLE
osx problem or wrong usage?

### ISSUE THREAD

**Issue by dasantonym** [denjello/VTT-Editor#3]
the mashup folder script writes an edl for each file but just writes one line each with `25.000` into those.

with verbose i get this output (no output mp4 file is written):

``` shell
unknown60F81DB21D5E:VTT-Editor anton$ ./mashup_folder.js -i=/Volumes/GHOSTSHARK/mash/ -o=/Volumes/GHOSTSHARK/mash.mp4 --system=osx -v=true
OPTIONS:-n=1 -x=1 -s=0.1 -y=osx -v=true -b=true 
file -b -k --mime-type  '/Volumes/GHOSTSHARK/mash/.DS_Store' | cut -d'/' -f1
file -b -k --mime-type  '/Volumes/GHOSTSHARK/mash/Decoder.avi' | cut -d'/' -f1
[detox.js] /Volumes/GHOSTSHARK/mash/Decoder.avi → safe
file -b -k --mime-type  '/Volumes/GHOSTSHARK/mash/House-Hausu-1977_720p_BRRip_x264_AAC-BeLLBoY-Kingdom-Release-.mp4' | cut -d'/' -f1
[detox.js] /Volumes/GHOSTSHARK/mash/House-Hausu-1977_720p_BRRip_x264_AAC-BeLLBoY-Kingdom-Release-.mp4 → safe
file -b -k --mime-type  '/Volumes/GHOSTSHARK/mash/Stan_Brakhage-Dog_Star_Man-1961-64,_Dvd-.avi' | cut -d'/' -f1
[detox.js] /Volumes/GHOSTSHARK/mash/Stan_Brakhage-Dog_Star_Man-1961-64,_Dvd-.avi → safe
file -b -k --mime-type  '/Volumes/GHOSTSHARK/mash/undefined' | cut -d'/' -f1
./edl_dropboring.js -i='/Volumes/GHOSTSHARK/mash/Decoder.avi' -o='/tmp/VTT-0' -n=1 -x=1 -s=0.1 -y=osx -v=true -b=true 
./edl_dropboring.js -i='/Volumes/GHOSTSHARK/mash/House-Hausu-1977_720p_BRRip_x264_AAC-BeLLBoY-Kingdom-Release-.mp4' -o='/tmp/VTT-1' -n=1 -x=1 -s=0.1 -y=osx -v=true -b=true 
./edl_dropboring.js -i='/Volumes/GHOSTSHARK/mash/Stan_Brakhage-Dog_Star_Man-1961-64,_Dvd-.avi' -o='/tmp/VTT-2' -n=1 -x=1 -s=0.1 -y=osx -v=true -b=true 
GLOBAL:  []
edlFinal: 
melt:
```

**Comment by denjello** [comment]
you'll have to play around with the sensitivity a bit. try `-s=0.001`

**Comment by denjello** [comment]
And remove `-b=true` > that is actually a method used by `mashup_folder.js` to signal 'edl_dropboring.js` not to render the job.

**Comment by dasantonym** [comment]
so i now saw that i already had 6 ffprobes running in background (while the script was already finished) and my load avg was up to 22. that was because i changed the log levels for ffprobe and made mplayer not-silent to dump the script output.

child_process has a max buffer size after which the process will be killed (SIGTERM i think). it is 200*1024. could this become a problem in some cases?

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

also, i noticed that sometimes the analyze script seems to let ffprobe run for ages (looking good) and just steps through the next files in milliseconds.

guess it would really be nice to see the output of the script in those cases (although i never got anything when dumping the values from the return function of child_process and changing the log level for ffprobe).

**Comment by dasantonym** [comment]
i'll try it in linux now. why exactly do i need to compile ffmpeg from the github source?

**Comment by denjello** [comment]
The thing is that the scoring of different films is necessarily different.

e.g. A video of the sky won't offer up much on the way of change, whereas people dancing changes all the time.

Try this:

`ffprobe -loglevel error -show_frames -of compact=p=0 -f lavfi "movie=bin/assets/SDV_0476.MP4,select=gt(scene\,0.001)"`

it gives something like this:
`
media_type=video|stream_index=0|key_frame=1|pkt_pts=2997600|pkt_pts_time=49.960000|pkt_dts=2997600|pkt_dts_time=49.960000|best_effort_timestamp=2997600|best_effort_timestamp_time=49.960000|pkt_duration=1200|pkt_duration_time=0.020000|pkt_pos=10257616|pkt_size=451584|width=448|height=336|pix_fmt=rgb24|sample_aspect_ratio=1:1|pict_type=I|coded_picture_number=0|display_picture_number=0|interlaced_frame=0|top_field_first=0|repeat_pict=0|tag:lavfi.scene_score=0.002825
`
This is the interesting bit: `lavfi.scene_score=0.002825`

**Comment by dasantonym** [comment]
did that and it gives me (among a million other lines):

``` shell
pkt_size=2073600|width=960|height=720|pix_fmt=rgb24|sample_aspect_ratio=1:1|pict_type=I|coded_picture_number=0|display_picture_number=0|interlaced_frame=0|top_field_first=0|repeat_pict=0|tag:lavfi.scene_score=0.448768
```

that score looks high enough to go over my threshold. but there are way less fields in my output.

**Comment by dasantonym** [comment]
oh copy & paste error i guess:

``` shell
media_type=video|key_frame=1|pkt_pts=11219208|pkt_pts_time=467.467000|pkt_dts=11219208|pkt_dts_time=467.467000|best_effort_timestamp=11219208|best_effort_timestamp_time=467.467000|pkt_duration=1001|pkt_duration_time=0.041708|pkt_pos=132815963|pkt_size=2073600|width=960|height=720|pix_fmt=rgb24|sample_aspect_ratio=1:1|pict_type=I|coded_picture_number=0|display_picture_number=0|interlaced_frame=0|top_field_first=0|repeat_pict=0|tag:lavfi.scene_score=0.004472
```

**Comment by denjello** [comment]
i know - the output is `sed`'d to get the frame where the scenchange happened.

`
ffprobe -loglevel error -show_frames -of compact=p=0 -f lavfi "movie=bin/assets/SDV_0476.MP4,select=gt(scene\,0.001)"  | sed -r 's/.*pkt_pts_time=([0-9.]{8,})\|.*/\1/'
`

**Comment by dasantonym** [comment]
so actually it should be filling up the edl files (at least tmp), right? then the error is somewhere else, maybe while extracting the data from the stdout?

**Comment by denjello** [comment]
FFMPEG BUILDER:

https://gist.github.com/denjello/7705937e693a4c49932a

**Comment by dasantonym** [comment]
i'll set up a vm especially for that as a last resort. but actually, if the probe command outputs all those values with time and difference and whatnot, i don't see why this can't work on my mac.

**Comment by dasantonym** [comment]
aha!

``` bash
unknown60F81DB21D5E:~ anton$ ffprobe -loglevel error -show_frames -of compact=p=0 -f lavfi "movie=/Volumes/GHOSTSHARK/mash/Decoder.avi,select=gt(scene\,0.001)"  | sed -r 's/.*pkt_pts_time=([0-9.]{8,})\|.*/\1/'
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Comment by dasantonym** [comment]
bsd-style sed has no -r option, but rather -E

**Comment by dasantonym** [comment]
ok i now get edls with content. running it now to see if it works. btw, the `-b=true` gets added automatically. i did not pass it to the mashup script.
